---
title: "Lab 06 - Conveying the right message through visualisation"
author: "Group 13.1"
output: github_document
---

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse) 
```


### Exercise 1

```{r create-data}

gdata <- c("Date", "Mask", "No Mask", "7/12/2020", 25.5, 20.9, "7/13/2022", 19.9, 20.6, "7/14/2022", 19.9, 20.5, "7/15/2022", 20.5, 20.9, "7/16/2020", 20.6, 20.9, "7/17/2022", 20, 19.8, "7/18/2020", 20.4, 20.4, "7/19/2020", 19.3, 19.4, "7/20/2020", 20.3, 19.4)

dates <- list("7/12/2020", "7/13/2022",  "7/14/2022", "7/15/2022", "7/16/2020", "7/17/2022", "7/18/2020", "7/19/2020", "7/20/2020")

mask_vals <- list(25.5, 19.9, 19.9, 20.5, 20.6, 20, 20.4, 19.3, 20.3)

no_mask_vals <- list(20.9, 20.6, 20.5, 20.9, 20.9, 19.8, 20.4, 19.4, 19.4)

df <- data.frame(unlist(dates), unlist(mask_vals), unlist(no_mask_vals))

names(df) <- c("Date", "Mask", "No Mask")



ggplot(df, aes(Date)
```


### Exercise 2

```{r better-viz}
# add code here
```


### Exercise 3

*Add your narrative here.*


### Exercise 4

*Add your narrative here.*
